### ISSUE TITLE
"500 Internal Server Error" when trying to use custom language model

### ISSUE THREAD

**Issue by malakhovks** [ljm625/syntaxnet-rest-api#4]
When trying to use custom language model
receive **500 Internal Server Error** from the server 

```
list index out of range
[2017-03-01 07:26:51,680] ERROR in app: Exception on /api/v1/query/English [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 481, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 510, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/representations/json.py", line 20, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: IndexError('list index out of range',) is not JSON serializable
[pid: 9|app: 0|req: 1/1] 192.168.1.103 () {40 vars in 565 bytes} [Wed Mar  1 07:26:36 2017] POST /api/v1/query/English => generated 37 bytes in 15486 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
```

**Comment by ljm625** [comment]
Thanks for the feedback, can you please send the payload you're testing?

**Comment by malakhovks** [comment]
For Russian language models 
[Russian](http://download.tensorflow.org/models/parsey_universal/Russian.zip)
[Russian-SynTagRus](http://download.tensorflow.org/models/parsey_universal/Russian-SynTagRus.zip)
```json
{
   "strings": ["Современные поисковые системы , осуществляющие поиск информации по ключевым словам используя лексические совпадения , имеют ряд недостатков , в частности , игнорируются такие явления , как полисемия и синонимия слов , так же не учитывается контекст в котором существует информация ." , "Персонифицированная база знаний научного исследователя – это открытая знание-ориентированная информационная система , представленная в виде компьютерной базы знаний ."]
}
```
For English language model [English](http://download.tensorflow.org/models/parsey_universal/English.zip)
```json
{
   "strings": ["I hope you are now beginning to understand the significance of this powerful parser ."] 
}
```

**Comment by ljm625** [comment]
Thanks for the feedback! I didn't realized there's a bug when the sentence is too long.. It should be fixed now :D

**Comment by malakhovks** [comment]
Fixed.

**Comment by ljm625** [comment]
Thanks for testing :P
